name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    if: github.repository == 'mobile-dev-inc/maestro'

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run detekt
        run: ./gradlew detekt --continue

      - name: Run tests
        run: ./gradlew test


  validate-gradle-wrapper:
    runs-on: ubuntu-latest
    name: Validate Gradle Wrapper

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
